services:
  app:
    build:
      context: .
    restart: always
    environment:
      SECRET_KEY: secret_key
      DATABASE_TYPE: mysql
      DATABASE_NAME: users
      MYSQL_HOST: db_mysql
      MYSQL_PORT: "3306"
      ADMIN_USER: admin # Mesmo valor de MYSQL_USER
      ADMIN_PASSWORD: admin # Mesmo valor de MYSQL_PASSWORD
    volumes:
      - ./log:/app/log
    ports:
      - 8080:8080
    networks:
      - appnet
    depends_on:
      - db_mysql

  db_mysql:
    image: mysql:9.0
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - appnet

networks:
  appnet:
    driver: bridge
