services:
  app:
    image: vitorbenites/compdistapp:1.0
    container_name: compdistapp
    restart: unless-stopped
    environment:
      SECRET_KEY: secret_key
      DATABASE_TYPE: mysql
      DATABASE_NAME: users # Mesmo valor de MYSQL_DATABASE
      MYSQL_HOST: db_mysql
      MYSQL_PORT: "3306"
      ADMIN_USER: admin # Mesmo valor de MYSQL_USER
      ADMIN_PASSWORD: admin # Mesmo valor de MYSQL_PASSWORD
    volumes:
      - ./log:/app/log
    ports:
      - 8080:8080
    networks:
      - appnet
    depends_on:
      - db_mysql

  db_mysql:
    image: mysql:9.1
    container_name: compdistapp_db
    restart: always
    environment:
      MYSQL_DATABASE: users
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    volumes:
      - ./database:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - appnet

networks:
  appnet:
    name: compdistapp_net
    driver: bridge
